name: deploy-test

on: 
  workflow_dispatch:
  issue_comment:
    types: [created, edited, deleted]

env:
  # Set the IMAGE_TAG in a way that works for both pull_request and push events.
  # For pull_request events, use github.event.pull_request.head.sha (see
  # https://github.com/actions/checkout#Checkout-pull-request-HEAD-commit-instead-of-merge-commit).
  # For push events, where github.event.pull_request.head.sha is not defined, use github.sha.
  IMAGE_TAG: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  Test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    environment: dev
    steps:
      - name: Check out code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Test
        run: echo "I should not run on comment, only manual click"

  Comment_Test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issue_comment' }}
    environment: dev
    steps:
      - name: Check out code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Test
        run: echo "I should only run on comment"